# Commands
SHIP_PLACEMENT_START_COMMAND = "PLACE_SHIPS_START"
SHIP_PLACEMENT_END_COMMAND = "PLACE_SHIPS_END"
CLIENT_SHIP_PLACEMENT_COMMAND = "PLACE_SHIPS"
CLIENT_SHOT_COMMAND = "FIRE"
SEE_BOARD_COMMAND = "SEE_BOARD"
QUIT_COMMAND = "QUIT"
TURN_COMMAND = "YOUR_TURN"
DISCONNECT_COMMAND = "DISCONNECT"

# Response flags
INVALID_REQUEST_FLAG = "INVALID"
INFO_FLAG = "INFO"
ERROR_FLAG = "ERROR"