# Commands
SHIP_PLACEMENT_START_COMMAND = "PLACE_SHIPS_START"
CLIENT_SHIP_PLACEMENT_COMMAND = "PLACE_SHIPS"
CLIENT_SHOT_COMMAND = "FIRE"
SEE_BOARD_COMMAND = "SEE_BOARD"
TURN_COMMAND = "YOUR_TURN"

# Response flags
INVALID_REQUEST_FLAG = "INVALID"
INFO_FLAG = "INFO"
ERROR_FLAG = "ERROR"